### ISSUE TITLE
Streaming I2S data to a BT sink

### ISSUE THREAD

**Issue by rmond18** [atomic14/esp32_audio#14]
Hi,

I'm trying to stream the audio of INMP441 w/ ESP32 to BT speakers/headphones, but I'm having a hard time figuring out how to stream the data continuously over Bluetooth to a BT sink. Do you have any tips/code? Thank you very much!

Regards,
rmond18

**Comment by cgreening** [comment]
Hi sorry for the delay in replying. There's a very good library here that will do exactly what you want:

https://github.com/pschatzmann/ESP32-A2DP
