### ISSUE TITLE
Further Explanation

### ISSUE THREAD

**Issue by calebmhopper** [atomic14/esp32_audio#15]
Hello, I am very new to programing. I am looking to create a wireless microphone system that works over a WIFI network for live sound reinforcement. I have everything downloaded, I am just not sure how to install everything and what parameters have to be modified to get it up and running. I was wondering if you could help walk me through how to get started. Ideally I would eventually like the received audio to come out of my server's speakers live.

Thanks in advance, I know those are a lot of questions.

-Caleb

**Comment by rmond18** [comment]
Hi Caleb,

This might be helpful for you:

https://youtu.be/5q5a5pee4ZQ

-Rmond
