### ISSUE TITLE
Typo in i2s sampling's main.cpp leads to wifiClientI2S never being used

### ISSUE THREAD

**Issue by JRVeale** [atomic14/esp32_audio#4]
In `void sendData()` I think line 59 should be:

`httpClient->begin(*wifiClient, url);` previously was `httpClient->begin(*wifiClientADC, url);`

Not something worth me making a PR for, but thought worth pointing out!

**Comment by cgreening** [comment]
Good spot! I'll fix this now.

**Comment by cgreening** [comment]
Fixed by e8a9e282ff3c8176209b757c8486f5d6c8ec1003
