### ISSUE TITLE
Noisy audio

### ISSUE THREAD

**Issue by caioyugo123** [atomic14/esp32_audio#8]
Hello, I've been trying to capture audio and send it via wifi just as described in the project. But, as soon as I play the RAW file, it is just a noisy audio without a trace of any captured voice. I checked over the code but didn't see anything wrong, although I'm very new to programming in general. I'll be linking the audio acquired via wifi. I'll be very much appreciated for any help, thanks.

[adc.zip](https://github.com/atomic14/esp32_audio/files/5564091/adc.zip)

**Comment by cgreening** [comment]
That's very strange. I would expect to see at least some recognisable audio.

Can you show me how the microphone is wired up? Which microphone board are you using?

**Comment by caioyugo123** [comment]
I am currently using a esp32 with a max9814 as the image attached below shows. I did a pass low filter, four 330ohm resistors in parallel with four 100microF capacitors also in parallel, in order to supply a more steady voltage in the Vpp pin. But it didn't change much as the audio shown. 

![Uploading 20201119_091652.jpg…]()

**Comment by caioyugo123** [comment]
I am currently using a esp32 with a max9814 as the image attached below shows. I did a pass low filter, four 330ohm resistors in parallel with four 100microF capacitors also in parallel, in order to supply a more steady voltage in the Vpp pin. But it didn't change much as the audio shown.

![10812d1d-0b16-49de-bf81-1ff32bacb956](https://user-images.githubusercontent.com/74694357/99667239-e0a83a80-2a4a-11eb-881c-17e05737aef0.jpg)

**Comment by cgreening** [comment]
I can't quite follow your low pass filter - I assume you get the noise even when you directly connect Vdd to 3v3?

You can try connecting the gain pin to 3v3 as well which will reduce the amount of gain the microphone is applying.

**Comment by caioyugo123** [comment]
I meant by doing as follows:

![dd368615-9b9e-45c0-a4c1-4c94d37551b4](https://user-images.githubusercontent.com/74694357/99688583-be231b00-2a64-11eb-8b96-ddb8b3b9c2e4.jpg)

I'll try connecting the gain pin.

**Comment by caioyugo123** [comment]
Ok, so I tried but it did not work. But, I noticed that during a certain time the audio caption worked. I was measuring voltage and poking the MAX9814 during the recording. Even though, I am not aware the reason why it worked.

[adc (2).zip](https://github.com/atomic14/esp32_audio/files/5568723/adc.2.zip)

**Comment by cgreening** [comment]
Can you try running the `loop_sampling` project? This will just output the value read from the ADC on the serial output.

In a quiet room, this should give you around 1.25v and it should range from about 0.25v to 2.25 volts when there is sound.

This will let us quickly check if the microphone is output sensible values.

**Comment by caioyugo123** [comment]
Ok, I just uploaded to the ESP32 and then monitored the serial monitor.

[serial monitor.txt](https://github.com/atomic14/esp32_audio/files/5568907/serial.monitor.txt)

**Comment by cgreening** [comment]
So, unless you are in a very noisy room this doesn't look good.

We should be seeing around 1250 for the mV values, but instead we are seeing some quite extreme values.

I would double check all your wiring and solder connections. It's also worth trying to power the the microphone from a battery as well just in case it's noise on the power line causing the issues. Two AA batteries will work.

**Comment by caioyugo123** [comment]
Unfortunately, it is not the case. Maybe I'll be testing with the loop sampling and will report any progress.
Also, I'll try buying these AA batteries.

**Comment by StuartIanNaylor** [comment]
Is it just me or is out connected to gnd? Its hard looking at a picture.
Oh no it does loop over.

On a Pi into a sound card those Max9814 are actually really good as long as you don't use the top gain (float).
40db/50db is loads of gain but the 60db seems wishful thinking.

Try this analogue mic as they are exceptionally good for noise https://www.ebay.co.uk/itm/ADMP401-MEMS-Microphone-Breakout-Module-Board-For-Arduino-Universal-1-3cm-1cm-UK/192101467145

I would post aliexpress but it seems to be doing the UK thing again.

Maybe its just the board and the ADC as I have a RockchipS RK3308 that is the same but on a pi via sound card great.
